#pragma config(Sensor, port1,   touchLED, sensorVexIQ_LED)
#pragma config(Motor,  motor4,  leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,  ladleMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,  fixatorMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10, rightLiftMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11, rightWheelMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12, leftWheelMotor, tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftWheelSpeed;
int leftWheelTarget;
int rightWheelSpeed;
int rightWheelTarget;

task main()
{
	init();
}

void init() {
  // init speed
  leftWheelSpeed = 0;
  rightWheelSpeed = 0;

  // init target
  leftWheelTarget = 0;
  rightWheelTarget = 0;

  resetMotorEncoder(rightWheelMotor);
  resetMotorEncoder(leftWheelMotor);
}
