#pragma config(Motor,  motor4,          leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          ladleMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          fixatorMotor,  tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         rightLiftMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         leftWheelMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightWheelMotor, tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define THRESHOLD_SPEED 20

#define FIXATOR_OFF "FIXATOR_OFF"
#define FIXATOR_ON "FIXATOR_ON"
#define LIFT_HIGH "LIFT_HIGH"
#define LIFT_LOW "LIFT_LOW"
#define LIFT_READY "LIFT_READY"
#define LADLE_READY "LADLE_READY"
#define LADLE_SHOOT "LADLE_SHOOT"
#define LADLE_TILT "LADLE_TILT"

#define LADLE_GEAR 2

task main()
{
	int leftSpeed = 0;
	int rightSpeed = 0;

	bool F_UP_PRESS_UP = true;
	bool F_DOWN_PRESS_UP = true;
	bool E_UP_PRESS_UP = true;
	bool R_UP_PRESS_UP = true;
	bool R_DOWN_PRESS_UP = true;
	bool L_UP_PRESS_UP = true;
	bool L_DOWN_PRESS_UP = true;

	string fixatorCurrent = FIXATOR_OFF;
	string fixatorReady = FIXATOR_OFF;

	string liftCurrent = LIFT_HIGH;
	string liftReady = LIFT_HIGH;

	string ladleCurrent = LADLE_READY;
	string ladleReady = LADLE_READY;

	int ladleDegress = 0;

	setMotorEncoderUnits(encoderDegrees);

	resetMotorEncoder(ladleMotor);
	setMotorBrakeMode(ladleMotor, motorHold);
	setMotorTarget(ladleMotor, 0, 80);

	while(true)
	{
		leftSpeed = 1.27 * getJoystickValue(ChA) - 1.27 * getJoystickValue(ChC);
		rightSpeed = 1.27 * getJoystickValue(ChA) + 1.27 * getJoystickValue(ChC);

		if (abs(leftSpeed) > THRESHOLD_SPEED)
		{
			setMotorSpeed(leftWheelMotor, leftSpeed);
		}
		else
		{
			setMotorSpeed(leftWheelMotor, 0);
		}

		if (abs(rightSpeed) > THRESHOLD_SPEED)
		{
			setMotorSpeed(rightWheelMotor, rightSpeed);
		}
		else
		{
			setMotorSpeed(rightWheelMotor, 0);
		}

		////////////////////////////////////////
		// F UP
		////////////////////////////////////////
		if(getJoystickValue(BtnFUp) == 1 && F_UP_PRESS_UP) {
			if (liftCurrent == LIFT_LOW) {
				liftReady = LIFT_HIGH;
			}

			if (liftCurrent == LIFT_READY) {
				liftReady = LIFT_LOW;
			}

			F_UP_PRESS_UP = false;
		}

		if(getJoystickValue(BtnFUp) == 0) {
			F_UP_PRESS_UP = true;
		}

		////////////////////////////////////////
		// F DOWN
		////////////////////////////////////////
		if(getJoystickValue(BtnFDown) == 1 && F_DOWN_PRESS_UP) {
			if (liftCurrent == LIFT_HIGH) {
				liftReady = LIFT_LOW;
			}

			if (liftCurrent == LIFT_LOW) {
				liftReady = LIFT_READY;
			}

			F_DOWN_PRESS_UP = false;
		}

		if(getJoystickValue(BtnFDown) == 0) {
			F_DOWN_PRESS_UP = true;
		}


		////////////////////////////////////////
		// E UP
		////////////////////////////////////////
		if(getJoystickValue(BtnEUp) == 1 && E_UP_PRESS_UP) {
			if (fixatorCurrent == FIXATOR_OFF) {
				fixatorReady = FIXATOR_ON;
			}

			if (fixatorCurrent == FIXATOR_ON) {
				fixatorReady = FIXATOR_OFF;
			}

			E_UP_PRESS_UP = false;
		}

		if(getJoystickValue(BtnEUp) == 0) {
			E_UP_PRESS_UP = true;
		}

		////////////////////////////////////////
		// R UP
		////////////////////////////////////////
		if (getJoystickValue(BtnRUp) == 1 && R_UP_PRESS_UP) {
			R_UP_PRESS_UP = false;
		}

		if (getJoystickValue(BtnRUp) == 0) {
			R_UP_PRESS_UP = true;
		}

		////////////////////////////////////////
		// R DOWN
		////////////////////////////////////////
		if (getJoystickValue(BtnRDown) == 1 && R_DOWN_PRESS_UP) {

			R_DOWN_PRESS_UP = false;
		}

		if (getJoystickValue(BtnRDown) == 0) {
			R_DOWN_PRESS_UP = true;
		}

		////////////////////////////////////////
		// L DOWN
		////////////////////////////////////////
		if (getJoystickValue(BtnLDown) == 1 && L_DOWN_PRESS_UP) {
			if (ladleCurrent == LADLE_READY) {
				ladleReady = LADLE_TILT;
			}

			if (ladleCurrent == LADLE_TILT) {
				ladleReady = LADLE_SHOOT;
			}

			if (ladleCurrent == LADLE_SHOOT) {
				ladleReady = LADLE_READY;
			}

			L_DOWN_PRESS_UP = false;
		}

		if (getJoystickValue(BtnLDown) == 0) {
			L_DOWN_PRESS_UP = true;
		}


		////////////////////////////////////////
		// L UP
		////////////////////////////////////////
		if (getJoystickValue(BtnLUp) == 1 && L_UP_PRESS_UP) {
			if (ladleCurrent == LADLE_READY) {
				ladleReady = LADLE_SHOOT;
			}

			if (ladleCurrent == LADLE_SHOOT) {
				ladleReady = LADLE_TILT;
			}

			if (ladleCurrent == LADLE_TILT) {
				ladleReady = LADLE_READY;
			}

			L_UP_PRESS_UP = false;
		}

		if (getJoystickValue(BtnLUp) == 0) {
			L_UP_PRESS_UP = true;
		}

		/////////////////////////////////////////
		// ladel state machine
		/////////////////////////////////////////
		if (ladleCurrent == LADLE_READY && ladleReady == LADLE_SHOOT) {
			ladleDegress += 180 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress - 10 * LADLE_GEAR, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_SHOOT && ladleReady == LADLE_TILT) {
			ladleDegress += 110 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_TILT && ladleReady == LADLE_READY) {
			ladleDegress += 70 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress + 5 * LADLE_GEAR, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_READY && ladleReady == LADLE_TILT) {
			ladleDegress -= 70 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_SHOOT && ladleReady == LADLE_READY) {
			ladleDegress -= 180 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress + 5 * LADLE_GEAR, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_TILT && ladleReady == LADLE_SHOOT) {
			ladleDegress -= 110 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress - 10 * LADLE_GEAR, 80);
			ladleCurrent = ladleReady;
		}

		/////////////////////////////////////////
		// fixator state machine
		/////////////////////////////////////////
		if (fixatorCurrent == FIXATOR_OFF && fixatorReady == FIXATOR_ON) {
			setMotorTarget(fixatorMotor, 220, 60);
			//wait(500);
			//setMotorTarget(leftLiftMotor, getMotorTarget(leftLiftMotor) - 100, 60);
			//setMotorTarget(rightLiftMotor, getMotorTarget(rightLiftMotor) - 100, 60);
			fixatorCurrent = fixatorReady;
		}

		if (fixatorCurrent == FIXATOR_ON && fixatorReady == FIXATOR_OFF) {
			setMotorTarget(fixatorMotor, 0, 100);
			fixatorCurrent = fixatorReady;
		}

		/////////////////////////////////////////
		// lift state machine
		/////////////////////////////////////////
		if (liftCurrent != liftReady && liftReady == LIFT_LOW) {
			setMotorTarget(leftLiftMotor, 550, 80);
			setMotorTarget(rightLiftMotor, 550, 80);
			liftCurrent = liftReady;
		}

		if (liftCurrent == LIFT_LOW && liftReady == LIFT_READY) {
			setMotorTarget(leftLiftMotor, 1200, 80);
			setMotorTarget(rightLiftMotor, 1200, 80);
			liftCurrent = liftReady;
		}

		if (liftCurrent == LIFT_LOW && liftReady == LIFT_HIGH) {
			setMotorTarget(leftLiftMotor, -30, 80);
			setMotorTarget(rightLiftMotor, -30, 80);
			liftCurrent = liftReady;
		}

		displayCenteredTextLine(0, "%s", ladleCurrent);
		displayCenteredTextLine(2, "%s", liftCurrent);
		displayCenteredTextLine(4, "%s", fixatorCurrent);
	}
}
