#pragma config(Motor,  motor4,          leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          ladleMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          fixatorMotor,  tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         rightLiftMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         leftWheelMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightWheelMotor, tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define THRESHOLD_SPEED 5

#define FIXATOR_OFF "FIXATOR_OFF"
#define FIXATOR_ON "FIXATOR_ON"

#define LIFT_HIGHER "LIFT_HIGHER"
#define LIFT_MIDDLE "LIFT_MIDDLE"
#define LIFT_LOWER "LIFT_LOWER"
#define LIFT_MANUAL "LIFT_MANUAL"

#define LIFT_HIGHER_INT_H -50
#define LIFT_HIGHER_INT -30
#define LIFT_HIGHER_INT_L 120

#define LIFT_MIDDLE_INT_H 500
#define LIFT_MIDDLE_INT 550
#define LIFT_MIDDLE_INT_L 600

#define LIFT_LOWER_INT_H 1150
#define LIFT_LOWER_INT 1200
#define LIFT_LOWER_INT_L 1250

#define LADLE_READY "LADLE_READY"
#define LADLE_SHOOT "LADLE_SHOOT"
#define LADLE_TILT "LADLE_TILT"

#define LADLE_GEAR 2

task main()
{
	int leftSpeed = 0;
	int rightSpeed = 0;

	bool F_UP_PRESS_UP = true;
	bool F_DOWN_PRESS_UP = true;
	bool E_UP_PRESS_UP = true;
	bool E_DOWN_PRESS_UP = true;
	bool R_UP_PRESS_UP = true;
	bool R_DOWN_PRESS_UP = true;
	bool L_UP_PRESS_UP = true;
	bool L_DOWN_PRESS_UP = true;

	string fixatorCurrent = FIXATOR_OFF;
	string fixatorReady = FIXATOR_OFF;

	string liftCurrent = LIFT_HIGHER;
	string liftReady = LIFT_HIGHER;

	string ladleCurrent = LADLE_READY;
	string ladleReady = LADLE_READY;

	int ladleDegress = 0;

	setMotorEncoderUnits(encoderDegrees);

	resetMotorEncoder(leftWheelMotor);
	resetMotorEncoder(rightWheelMotor);
	resetMotorEncoder(ladleMotor);
	resetMotorEncoder(fixatorMotor);

	setMotorBrakeMode(ladleMotor, motorHold);
	setMotorTarget(ladleMotor, 0, 80);

	setMotorBrakeMode(leftWheelMotor, motorBrake);
	setMotorBrakeMode(rightWheelMotor, motorBrake);

	setMotorBrakeMode(fixatorMotor, motorHold);
	setMotorBrakeMode(leftLiftMotor, motorHold);
	setMotorBrakeMode(rightLiftMotor, motorHold);

	while(true)
	{
		leftSpeed = getJoystickValue(ChA) - getJoystickValue(ChC);
		rightSpeed = getJoystickValue(ChA) + getJoystickValue(ChC);

		if (abs(leftSpeed) >= THRESHOLD_SPEED && abs(leftSpeed) < 50)
		{
			setMotorSpeed(leftWheelMotor, leftSpeed * 0.5);
		}
		else if (abs(leftSpeed) >= 50 && abs(leftSpeed) < 80)
		{
			setMotorSpeed(leftWheelMotor, leftSpeed);
		}
		else if (abs(leftSpeed) >= 80 && abs(leftSpeed) <= 200)
		{
			setMotorSpeed(leftWheelMotor, leftSpeed * 1.25);
		}
		else
		{
			setMotorSpeed(leftWheelMotor, 0);
		}

		if (abs(rightSpeed) > THRESHOLD_SPEED && abs(rightSpeed) < 50)
		{
			setMotorSpeed(rightWheelMotor, rightSpeed * 0.5);
		}
		else if (abs(rightSpeed) >= 50 && abs(rightSpeed) < 80)
		{
			setMotorSpeed(rightWheelMotor, rightSpeed);
		}
		else if (abs(rightSpeed) >= 80 && abs(rightSpeed) <= 200)
		{
			setMotorSpeed(rightWheelMotor, rightSpeed * 1.25);
		}
		else
		{
			setMotorSpeed(rightWheelMotor, 0);
		}

		////////////////////////////////////////
		// F UP
		////////////////////////////////////////
		if(getJoystickValue(BtnFUp) == 1 && F_UP_PRESS_UP) {
			int currentTarget = getMotorTarget(leftLiftMotor);

			if (currentTarget < LIFT_LOWER_INT_L && currentTarget > LIFT_MIDDLE_INT_L)
			{
				setMotorTarget(leftLiftMotor, LIFT_MIDDLE_INT, 80);
				setMotorTarget(rightLiftMotor, LIFT_MIDDLE_INT, 80);
			}
			else if (currentTarget < LIFT_MIDDLE_INT_L && currentTarget > LIFT_HIGHER_INT_H)
			{
				setMotorTarget(leftLiftMotor, LIFT_HIGHER_INT, 80);
				setMotorTarget(rightLiftMotor, LIFT_HIGHER_INT, 80);
			}

			F_UP_PRESS_UP = false;
		}

		if(getJoystickValue(BtnFUp) == 0) {
			F_UP_PRESS_UP = true;
		}

		////////////////////////////////////////
		// F DOWN
		////////////////////////////////////////
		if(getJoystickValue(BtnFDown) == 1 && F_DOWN_PRESS_UP) {
			int currentTarget = getMotorTarget(leftLiftMotor);

			if (currentTarget > LIFT_HIGHER_INT_H && currentTarget < LIFT_MIDDLE_INT_H)
			{
				setMotorTarget(leftLiftMotor, LIFT_MIDDLE_INT, 80);
				setMotorTarget(rightLiftMotor, LIFT_MIDDLE_INT, 80);
			}
			else if (currentTarget > LIFT_MIDDLE_INT_H && currentTarget < LIFT_LOWER_INT_H)
			{
				setMotorTarget(leftLiftMotor, LIFT_LOWER_INT, 80);
				setMotorTarget(rightLiftMotor, LIFT_LOWER_INT, 80);
			}

			F_DOWN_PRESS_UP = false;
		}

		if(getJoystickValue(BtnFDown) == 0) {
			F_DOWN_PRESS_UP = true;
		}


		////////////////////////////////////////
		// E UP
		////////////////////////////////////////
		if(getJoystickValue(BtnEUp) == 1 && E_UP_PRESS_UP) {
			if (fixatorCurrent == FIXATOR_OFF) {
				fixatorReady = FIXATOR_ON;
			}

			if (fixatorCurrent == FIXATOR_ON) {
				fixatorReady = FIXATOR_OFF;
			}

			E_UP_PRESS_UP = false;
		}

		if(getJoystickValue(BtnEUp) == 0) {
			E_UP_PRESS_UP = true;
		}

		////////////////////////////////////////
		// E DOWN
		////////////////////////////////////////
		if(getJoystickValue(BtnEDown) == 1 && E_DOWN_PRESS_UP) {
			int currentTarget = getMotorTarget(leftLiftMotor);

			if (currentTarget > LIFT_HIGHER_INT_L && currentTarget < LIFT_LOWER_INT_L)
			{
				setMotorTarget(leftLiftMotor, currentTarget - 100, 60);
				setMotorTarget(rightLiftMotor, currentTarget - 100, 60);
			}

			E_DOWN_PRESS_UP = false;
		}

		if(getJoystickValue(BtnEDown) == 0) {
			E_DOWN_PRESS_UP = true;
		}

		////////////////////////////////////////
		// R UP
		////////////////////////////////////////
		if (getJoystickValue(BtnRUp) == 1 && R_UP_PRESS_UP) {
			setMotorTarget(leftLiftMotor, 150, 80);
			setMotorTarget(rightLiftMotor, 150, 80);

			R_UP_PRESS_UP = false;
		}

		if (getJoystickValue(BtnRUp) == 0) {
			R_UP_PRESS_UP = true;
		}

		////////////////////////////////////////
		// R DOWN
		////////////////////////////////////////
		if (getJoystickValue(BtnRDown) == 1 && R_DOWN_PRESS_UP) {
			setMotorTarget(leftLiftMotor, 360, 80);
			setMotorTarget(rightLiftMotor, 360, 80);

			wait(100, milliseconds);

			setMotorSpeed(leftWheelMotor, 120);
			setMotorSpeed(rightWheelMotor, 120);

			wait(550, milliseconds);

			setMotorSpeed(leftWheelMotor, 0);
			setMotorSpeed(rightWheelMotor, 0);

			setMotorTarget(leftLiftMotor, 150, 80);
			setMotorTarget(rightLiftMotor, 150, 80);


			R_DOWN_PRESS_UP = false;
		}

		if (getJoystickValue(BtnRDown) == 0) {
			R_DOWN_PRESS_UP = true;
		}

		////////////////////////////////////////
		// L DOWN
		////////////////////////////////////////
		if (getJoystickValue(BtnLDown) == 1 && L_DOWN_PRESS_UP) {
			if (ladleCurrent == LADLE_READY) {
				ladleReady = LADLE_TILT;
			}

			if (ladleCurrent == LADLE_TILT) {
				ladleReady = LADLE_SHOOT;
			}

			if (ladleCurrent == LADLE_SHOOT) {
				ladleReady = LADLE_READY;
			}

			L_DOWN_PRESS_UP = false;
		}

		if (getJoystickValue(BtnLDown) == 0) {
			L_DOWN_PRESS_UP = true;
		}


		////////////////////////////////////////
		// L UP
		////////////////////////////////////////
		if (getJoystickValue(BtnLUp) == 1 && L_UP_PRESS_UP) {
			if (ladleCurrent == LADLE_READY) {
				ladleReady = LADLE_SHOOT;
			}

			if (ladleCurrent == LADLE_SHOOT) {
				ladleReady = LADLE_TILT;
			}

			if (ladleCurrent == LADLE_TILT) {
				ladleReady = LADLE_READY;
			}

			L_UP_PRESS_UP = false;
		}

		if (getJoystickValue(BtnLUp) == 0) {
			L_UP_PRESS_UP = true;
		}

		/////////////////////////////////////////
		// ladel state machine
		/////////////////////////////////////////
		if (ladleCurrent == LADLE_READY && ladleReady == LADLE_SHOOT) {
			ladleDegress += 180 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress - 10 * LADLE_GEAR, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_SHOOT && ladleReady == LADLE_TILT) {
			ladleDegress += 110 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_TILT && ladleReady == LADLE_READY) {
			ladleDegress += 70 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress + 5 * LADLE_GEAR, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_READY && ladleReady == LADLE_TILT) {
			ladleDegress -= 70 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_SHOOT && ladleReady == LADLE_READY) {
			ladleDegress -= 180 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress + 5 * LADLE_GEAR, 80);
			ladleCurrent = ladleReady;
		}

		if (ladleCurrent == LADLE_TILT && ladleReady == LADLE_SHOOT) {
			ladleDegress -= 110 * LADLE_GEAR;
			setMotorTarget(ladleMotor, ladleDegress - 10 * LADLE_GEAR, 80);
			ladleCurrent = ladleReady;
		}

		/////////////////////////////////////////
		// fixator state machine
		/////////////////////////////////////////
		if (fixatorCurrent == FIXATOR_OFF && fixatorReady == FIXATOR_ON) {
			setMotorTarget(fixatorMotor, 210, 80);
			fixatorCurrent = fixatorReady;
		}

		if (fixatorCurrent == FIXATOR_ON && fixatorReady == FIXATOR_OFF) {
			setMotorTarget(fixatorMotor, 0, 100);
			fixatorCurrent = fixatorReady;
		}

		displayCenteredTextLine(0, "%s", ladleCurrent);
		displayCenteredTextLine(2, "%s", fixatorCurrent);
		displayCenteredTextLine(4, "LIFT_TARGET %d", getMotorTarget(leftLiftMotor));
	}
}
