#pragma config(Sensor, port12,  TouchLED1,      sensorVexIQ_LED)
#pragma config(Sensor, port7,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          rightarmMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          rightMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          GouMotor,      tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          ClawMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          leftMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          leftarmMotor,  tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 1   UpDown_LeftArm(nDegree,nSpeed,nGoTime);
// 2   UpDown_RightArm(nDegree,nSpeed,nGoTime);
// 3   UpDown_Gou(nDegree,nSpeed,nGoTime);
// 4   Go_Forward_Distance(nDistance, nSpeed,nMaxTime);
// 5   Go_Forward_Time(nSpeed,nGoTime,nFactor);
// 6   Gyro_Rotation(nDegree,nSpeed,nMaxTime);

//	1nAct,2nSpeed,3nDegree,4nDistance,5nGoTime,6nMaxtime,7nFactor;

/*
int Act[30][7]={
	{1,20,60,0,600,0,0},     // 1   UpDown_Gou(nSpeed,nDegree,nGoTime);
	{1,20,0,0,600,0,0},      // 1   UpDown_Gou(nSpeed,nDegree,nGoTime);
	{2,20,70,0,500,0,0},     // 2   UpDown_Claw(nSpeed,nDegree,nGoTime);
	{2,20,0,0,500,0,0},      // 2   UpDown_Claw(nSpeed,nDegree,nGoTime);
	{3,20,80,0,500,0,0},     // 3   UpDown_Arm(nSpeed,nDegree,nGoTime);
	{3,20,0,0,500,0,0},      // 3   UpDown_Arm(nSpeed,nDegree,nGoTime);
	{4,20,0,360,0,5000,0},   // 4   Go_Forward_Distance(nSpeed,nDistance, nMaxTime);
	{4,-20,0,360,0,5000,0},  // 4   Go_Forward_Distance(nSpeed,nDistance, nMaxTime);
	{5,20,0,100,300,0,95},   // 5   Go_Forward_Time(nSpeed,nGoTime,nFactor);
	{5,-20,0,100,300,0,110}, // 5   Go_Forward_Time(nSpeed,nGoTime,nFactor);
	{6,20,30,0,0,5000,0},	   // 6   Gyro_Rotation(nDegree,nSpeed,nMaxTime);
	{6,-20,20,0,0,5000,0},   //	6   Gyro_Rotation(nDegree,nSpeed,nMaxTime);
};
*/
//	1nAct,2nSpeed,3nDegree,4nDistance,5nGoTime,6nMaxtime,nFactor;
int Act[75][7]={

	{6,20,50,0,0,5000,0},    // 1   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
	{5,50,0,0,1100,0,100},    // 2   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{6,-20,100,0,0,5000,0},    // 3   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
	{5,30,0,0,600,0,100},    // 4   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{3,100,300,0,1000,0,0},      // 5   UpDown_Arm(nSpeed,nDegree,nGoTime);5
	{5,50,0,0,800,0,100},    // 6   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{6,20,30,0,0,5000,0},    // 7   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
	{5,50,0,0,850,0,100},    // 8   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{3,30,180,0,500,0,0},      // 9   UpDown_Arm(nSpeed,nDegree,nGoTime);5
	{5,-100,0,0,1200,0,100},    // 10   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{5,-50,0,0,500,0,100},    // 11  Go_Forward_Time(nSpeed,nGoTime,nFactor);4
//***********20OK**************************************************************


//********40-ok***************************************************************************************
	{3,50,0,0,1000,0,0},      // 12   UpDown_Arm(nSpeed,nDegree,nGoTime);5

	{6,20,45,0,0,5000,0},    // 13   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
  {5,50,0,0,1700,0,100},    // 14   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{3,100,300,0,1000,0,0},      // 15   UpDown_Arm(nSpeed,nDegree,nGoTime);5
  {5,50,0,0,1700,0,100},    // 16   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{6,-20,6,0,0,5000,0},    // 17   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
  {5,50,0,0,500,0,100},    // 18   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{3,30,180,0,1000,0,0},      // 19   UpDown_Arm(nSpeed,nDegree,nGoTime);5
  {5,-100,0,0,2000,0,100},    // 20   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{3,50,0,0,1000,0,0},      // 21   UpDown_Arm(nSpeed,nDegree,nGoTime);5



//*****20-ok*************************************************************************
//*******************************************************************************

	{5,50,0,0,580,0,100},    // 22   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{6,20,85,0,0,5000,0},    // 23   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
	{5,-50,0,0,1300,0,100},    // 24   Go_Forward_Time(nSpeed,nGoTime,nFactor);	6  backword
	{1,100,150,0,300,0,0},     // 25   UpDown_Gou(nSpeed,nDegree,nGoTime);

	{5,50,0,0,200,0,100},    // 26   Go_Forward_Time(nSpeed,nGoTime,nFactor);8
	{6,-20,81,0,0,5000,0},    // 27   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
	{5,50,0,0,1300,0,100},    // 28   Go_Forward_Time(nSpeed,nGoTime,nFactor);8
	{3,100,300,0,1000,0,0},      // 29   UpDown_Arm(nSpeed,nDegree,nGoTime);5
	{5,-50,0,0,900,0,100},    //30   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{6,20,20,0,0,5000,0},    // 31   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
	{5,50,0,0,600,0,100},    // 32   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{6,20,65,0,0,5000,0},    // 33   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
	//***2  qiu---ok**************************************************************

  {5,50,0,0,1600,0,100},    // 34   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	//{6,-20,5,0,0,5000,0},    // 35   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
  {5,50,0,0,2400,0,100},    // 36   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{6,20,8,0,0,5000,0},    // 37   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
	{3,50,0,0,1000,0,0},      // 38   UpDown_Arm(nSpeed,nDegree,nGoTime);5
  {5,100,0,0,1500,0,100},    // 39   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
//*******30----OK*****************************************************************
  {5,-50,0,0,500,0,100},    // 40   Go_Forward_Time(nSpeed,nGoTime,nFactor);4

	{6,20,100,0,0,5000,0},    // 41   Gyro_Rotation(nDegree,nSpeed,nMaxTime);3//20du
  {5,-100,0,0,1800,0,100},    // 42   Go_Forward_Time(nSpeed,nGoTime,nFactor);4
	{1,50,0,0,300,0,0},     // 43   UpDown_Gou(nSpeed,nDegree,nGoTime);
  {5,100,0,0,800,0,100},    // 44   Go_Forward_Time(nSpeed,nGoTime,nFactor);4



};

//	nAct,nSpeed,nDegree,nDistance,nGoTime,nMaxtime,nFactor;
void Init_Car();


void UpDown_Gou(int nSpeed,int nDegree,int nDelayTime);

void UpDown_Claw(int nSpeed,int nDegree,int nDelayTime);

void UpDown_Arm(int nSpeed,int nDegree,int nDelayTime);


void Gyro_Rotation(int nSpeed,int nDegree,int nMaxTime);

void Go_Forward_Distance(int nSpeed,int nDistance,int nMaxTime);

void Go_Forward_Time(int nSpeed, int nDelay,int nFactor);


//main *****************************************************************
task main()
{
	int i;
	 int nAct;    //
   int nSpeed;
	 int nDegree;
	 int nDistance;
	 int nGoTime;
	 int nMaxtime;
	 int nFactor;
	 Init_Car();

//	 UpDown_Arm(100,400,1500);

setTouchLEDColor(TouchLED1, colorRed);     // set touch LED color as Red
waitUntil((getTouchLEDValue(TouchLED1)==1)); // wait touch
setTouchLEDColor(TouchLED1, colorGreen);   // when touch LED, its color change to Green

	 for(i=0;i<11;i++)
	 {
	     nAct=Act[i][0];    //
       nSpeed=Act[i][1];
	     nDegree=Act[i][2];
	     nDistance=Act[i][3];
	     nGoTime=Act[i][4];
	     nMaxtime=Act[i][5];
	     nFactor=Act[i][6];



	     //while(i==11);//******************************************


	     switch(nAct)
	     {
	         case 1:
	             UpDown_Gou(nSpeed,nDegree,nGoTime);
	         break;
	         case 2:
	             UpDown_Claw(nSpeed,nDegree,nGoTime);
	         break;
	         case 3:
	             UpDown_Arm(nSpeed,nDegree,nGoTime);
	         break;
	         case 4:
	             Go_Forward_Distance(nSpeed,nDistance, nMaxTime);
	         break;
	         case 5:
	             Go_Forward_Time(nSpeed,nGoTime,nFactor);
	         break;
	         case 6:
	              Gyro_Rotation(nSpeed,nDegree,nMaxTime);
	         break;
	     }
	  delay(50);

	  }

		setTouchLEDColor(TouchLED1, colorRed);     // set touch LED color as Red
		waitUntil((getTouchLEDValue(TouchLED1)==1)); // wait touch
		setTouchLEDColor(TouchLED1, colorGreen);   // when touch LED, its color change to Green

	 for(i=11;i<21;i++)
	 {
	     nAct=Act[i][0];    //
       nSpeed=Act[i][1];
	     nDegree=Act[i][2];
	     nDistance=Act[i][3];
	     nGoTime=Act[i][4];
	     nMaxtime=Act[i][5];
	     nFactor=Act[i][6];



	    // while(i==21);//******************************************


	     switch(nAct)
	     {
	         case 1:
	             UpDown_Gou(nSpeed,nDegree,nGoTime);
	         break;
	         case 2:
	             UpDown_Claw(nSpeed,nDegree,nGoTime);
	         break;
	         case 3:
	             UpDown_Arm(nSpeed,nDegree,nGoTime);
	         break;
	         case 4:
	             Go_Forward_Distance(nSpeed,nDistance, nMaxTime);
	         break;
	         case 5:
	             Go_Forward_Time(nSpeed,nGoTime,nFactor);
	         break;
	         case 6:
	              Gyro_Rotation(nSpeed,nDegree,nMaxTime);
	         break;
	     }
	  delay(50);

	  }

setTouchLEDColor(TouchLED1, colorRed);     // set touch LED color as Red
waitUntil((getTouchLEDValue(TouchLED1)==1)); // wait touch
setTouchLEDColor(TouchLED1, colorGreen);   // when touch LED, its color change to Green

	 for(i=21;i<44;i++)
	 {
	     nAct=Act[i][0];    //
       nSpeed=Act[i][1];
	     nDegree=Act[i][2];
	     nDistance=Act[i][3];
	     nGoTime=Act[i][4];
	     nMaxtime=Act[i][5];
	     nFactor=Act[i][6];



	     //while(i==43);//******************************************


	     switch(nAct)
	     {
	         case 1:
	             UpDown_Gou(nSpeed,nDegree,nGoTime);
	         break;
	         case 2:
	             UpDown_Claw(nSpeed,nDegree,nGoTime);
	         break;
	         case 3:
	             UpDown_Arm(nSpeed,nDegree,nGoTime);
	         break;
	         case 4:
	             Go_Forward_Distance(nSpeed,nDistance, nMaxTime);
	         break;
	         case 5:
	             Go_Forward_Time(nSpeed,nGoTime,nFactor);
	         break;
	         case 6:
	              Gyro_Rotation(nSpeed,nDegree,nMaxTime);
	         break;
	     }
	  delay(50);

	  }
}
void Init_Car()
{
//	setMotorEncoderUnits(encoderDegrees);
	resetMotorEncoder(rightarmMotor);
	resetMotorEncoder(ClawMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftarmMotor);
	resetMotorEncoder(gouMotor);
	resetMotorEncoder(LeftMotor);
}

void UpDown_Gou(int nSpeed,int nDegree,int nDelayTime)
{
		setMotorTarget(gouMotor, nDegree, nSpeed);
	  delay(nDelayTime);
		setMotorTarget(gouMotor, nDegree, 0);
}

void UpDown_Claw(int nSpeed,int nDegree,int nDelayTime)
{
		setMotorTarget(ClawMotor, nDegree, nSpeed);
	  delay(nDelayTime);
		setMotorTarget(ClawMotor, nDegree, 0);
}

void UpDown_Arm(int nSpeed,int nDegree,int nDelayTime)
{
		setMotorTarget(leftarmMotor, nDegree, nSpeed);
		setMotorTarget(rightarmMotor, nDegree, nSpeed);
	  delay(nDelayTime);
		setMotorTarget(leftarmMotor, nDegree, 0);
		setMotorTarget(rightarmMotor, nDegree, 0);
}

void Gyro_Rotation(int nSpeed,int nDegree,int nMaxTime)
{
	int real_degree = 0;
	clearTimer(T1); // Resets timer T1 to start counting at 0
	resetGyro(Gyro);
	real_degree = abs(getGyroHeading(Gyro));
	setMotorSpeed(LeftMotor,  nSpeed);
	setMotorSpeed(rightMotor, -nSpeed);
  while(real_degree<nDegree)
  {
  	real_degree = abs(getGyroHeading(Gyro));
		displayTextLine(2, "%d", real_degree);
		if(time1[T1] >nMaxTime)
		{
		  	playNote(noteCSharp, octave2,  200);
		    break;
		}
  }
	setMotorSpeed(LeftMotor,  0);
	setMotorSpeed(rightMotor, 0);
}


/*

*/
void Go_Forward_Distance(int nSpeed,int nDistance,int nMaxTime)
{
	int nTarget_Degree;
	int nDegree_Temp;
	clearTimer(T1); // Resets timer T1 to start counting at 0
	nTarget_Degree=(float)nDistance/200*360;
	resetMotorEncoder(LeftMotor);
	//setMotorTarget(LeftMotor,nTarget_Degree,nSpeed);
	//setMotorTarget(rightMotor,nTarget_Degree,nSpeed);

	setMotorSpeed(LeftMotor, nSpeed);
	setMotorSpeed(rightMotor, nSpeed);
	nDegree_Temp=getServoEncoder(LeftMotor);

	while(nDegree_Temp<nTarget_Degree) //while the Sonar Sensor read data greater than '20':
  {
	  nDegree_Temp=abs(getServoEncoder(LeftMotor));
		displayTextLine(2, "%d", nDegree_Temp);
		if(time1[T1] >nMaxTime)
		{
		  	playNote(noteCSharp, octave2,  200);
		    break;
		}
  }
	setMotorSpeed(LeftMotor, 0);
	setMotorSpeed(rightMotor, 0);
}



/*

*/
void Go_Forward_Time(int nSpeed, int nDelay,int nFactor)
{
	int nSpeedTemp;
	int nDelayTemp;
	int i;
	float fFactor;
	int nLeftSpeed,nRightSpeed;
	fFactor=(float)nFactor/100;
	nSpeedTemp=nSpeed/5;
	nDelayTemp=nDelay/50;
	for(i=1;i<=5;i++)
	{
		nLeftSpeed=nSpeedTemp*i;
		nRightSpeed=nLeftSpeed*fFactor;
		setMotorSpeed(LeftMotor, nLeftSpeed);
		setMotorSpeed(rightMotor, nRightSpeed);
		delay(5);
	}
	delay(nDelay-50);
	for(i=5;i>=1;i--)
	{
		nLeftSpeed=nSpeedTemp*i;
		nRightSpeed=nLeftSpeed*fFactor;
		setMotorSpeed(LeftMotor, nLeftSpeed);
		setMotorSpeed(rightMotor, nRightSpeed);
		delay(5);
	}
	setMotorSpeed(LeftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	delay(5);
}
