#pragma config(Motor,  motor2,          leftArmMotor,  tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          leftLadleMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          leftWheelMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          rightArmMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          rightLadleMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         rightWheelMotor, tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define THRESHOLD_SPEED 20

task main()
{
	int leftSpeed = 0;
	int rightSpeed = 0;

	while(true)
	{
		leftSpeed = 1.27 * getJoystickValue(ChA) + 1.27 * getJoystickValue(ChC);
		rightSpeed = 1.27 * getJoystickValue(ChA) - 1.27 * getJoystickValue(ChC);

		if (abs(leftSpeed) > THRESHOLD_SPEED)
		{
			setMotorSpeed(leftWheelMotor, leftSpeed);
		}
		else
		{
			setMotorSpeed(leftWheelMotor, 0);
		}

		if (abs(rightSpeed) > THRESHOLD_SPEED)
		{
			setMotorSpeed(rightWheelMotor, rightSpeed);
		}
		else
		{
			setMotorSpeed(rightWheelMotor, 0);
		}

		if(getJoystickValue(BtnFUp) == 1)
		{
			setMotorTarget(leftArmMotor, 220, 100);
			setMotorTarget(rightArmMotor, 220, 100);
		}
		else if(getJoystickValue(BtnFDown) == 1)
		{
			setMotorTarget(leftArmMotor, 0, 50);
			setMotorTarget(rightArmMotor, 0, 50);
		}
		else
		{
			setMotorSpeed(leftArmMotor, 0);
			setMotorSpeed(rightArmMotor, 0);
		}

		resetMotorEncoder(leftLadleMotor);
		resetMotorEncoder(rightLadleMotor);

		if(getJoystickValue(BtnRUp) == 1)
		{
			setMotorSpeed(leftLadleMotor, -130);
			setMotorSpeed(rightLadleMotor, -130);
		}
		else if(getJoystickValue(BtnRDown) == 1)
		{
			setMotorSpeed(leftLadleMotor, -130);
			setMotorSpeed(rightLadleMotor, -130);
		}
		else if(getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(leftLadleMotor, 130);
			setMotorSpeed(rightLadleMotor, 130);
		}
		else if(getJoystickValue(BtnLDown) == 1)
		{
			setMotorSpeed(leftLadleMotor, 130);
			setMotorSpeed(rightLadleMotor, 130);
		}
		else
		{
			setMotorSpeed(leftLadleMotor, 0);
			setMotorSpeed(rightLadleMotor,0);
		}
	}
}
