#pragma config(Motor,  motor1,          leftWheelMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          leftLadleMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          leftArmMotor,  tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          rightWheelMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          rightLadleMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          rightArmMotor, tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define THRESHOLD_SPEED 20

task main()
{
	int leftSpeed = 0;
	int rightSpeed = 0;

	while(true)
	{
		leftSpeed = 1.27 * getJoystickValue(ChA) + 1.27 * getJoystickValue(ChC);
		rightSpeed = 1.27 * getJoystickValue(ChA) - 1.27 * getJoystickValue(ChC);

		if (abs(leftSpeed) > THRESHOLD_SPEED)
		{
			setMotorSpeed(leftWheelMotor, leftSpeed);
		}
		else
		{
			setMotorSpeed(leftWheelMotor, 0);
		}

		if (abs(rightSpeed) > THRESHOLD_SPEED)
		{
			setMotorSpeed(rightWheelMotor, rightSpeed);
		}
		else
		{
			setMotorSpeed(rightWheelMotor, 0);
		}

		if(getJoystickValue(BtnFUp) == 1)
		{
			setMotorTarget(leftArmMotor, 190, 100);
			setMotorTarget(rightArmMotor, 190, 100);
		}
		else if(getJoystickValue(BtnFDown) == 1)
		{
			setMotorTarget(leftArmMotor, 0, 50);
			setMotorTarget(rightArmMotor, 0, 50);
		}
		else if(getJoystickValue(BtnEUp) == 1)
		{
			setMotorTarget(leftArmMotor, 150, 50);
			setMotorTarget(rightArmMotor, 150, 50);
		}
		else if(getJoystickValue(BtnEDown) == 1)
		{
			setMotorTarget(leftArmMotor, 120, 50);
			setMotorTarget(rightArmMotor, 120, 50);
		}
		else
		{
			setMotorSpeed(leftArmMotor, 0);
			setMotorSpeed(rightArmMotor, 0);
		}

		resetMotorEncoder(leftLadleMotor);
		resetMotorEncoder(rightLadleMotor);

		if(getJoystickValue(BtnRUp) == 1)
		{
			setMotorTarget(leftLadleMotor,400, 100);
			setMotorTarget(rightLadleMotor, 400, 100);
			wait1Msec(1200);
			setMotorTarget(leftLadleMotor,0, 100);
			setMotorTarget(rightLadleMotor,0, 100);
			wait1Msec(900);
		}
		else if(getJoystickValue(BtnRDown) == 1)
		{
			setMotorTarget(leftLadleMotor, 906, 100);
			setMotorTarget(rightLadleMotor, 906, 100);
			wait1Msec(2200);
		}
		else if(getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(leftLadleMotor, 100);
			setMotorSpeed(rightLadleMotor, 100);
		}
		else if(getJoystickValue(BtnLDown) == 1)
		{
			setMotorSpeed(leftLadleMotor, -100);
			setMotorSpeed(rightLadleMotor, -100);
		}
		else
		{
			setMotorSpeed(leftLadleMotor, 0);
			setMotorSpeed(rightLadleMotor,0);
		}
	}
}
