#pragma config(Motor,  motor4,          leftMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          leftkouqiuMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          leftarmMotor,  tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,          rightMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,          rightkouqiuMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,          rightarmMotor, tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int threshold = 20;
	int ls = 0;int rs = 0;
	//int zerodegree;
   //zerodegree=getMotorZeroPosition(leftkouqiuMotor);

	while(true)
	{
		// !!xiang qian!!
		ls = 1.27*getJoystickValue(ChA) + getJoystickValue(ChC)*1.27;
		rs = 1.27*getJoystickValue(ChA) - getJoystickValue(ChC)*1.27;

		if (ls > threshold || ls < -threshold)
		{
			setMotorSpeed(leftMotor, ls);
		}
		else
		{
			setMotorSpeed(leftMotor, 0);
		}
		if (rs > threshold || rs < -threshold)

		{
			setMotorSpeed(rightMotor, rs);
		}
		else
		{
			setMotorSpeed(rightMotor, 0);
		}
//armMotor*****************************************************************

		if(getJoystickValue(BtnFUp) == 1)
		{
			setMotorTarget(leftarmMotor, 190, 100);
			setMotorTarget(rightarmMotor, 190, 100);
		}

		else if(getJoystickValue(BtnFDown) == 1)
		{
			setMotorTarget(leftarmMotor, 0,50);
			setMotorTarget(rightarmMotor,0,50);
		}
		else if(getJoystickValue(BtnEUp) == 1)
		{
		  setMotorTarget(leftarmMotor, 150, 50);
			setMotorTarget(rightarmMotor,150, 50);
		}
		else if(getJoystickValue(BtnEDown) == 1)
		{
		  setMotorTarget(leftarmMotor, 120, 50);
			setMotorTarget(rightarmMotor,120, 50);
		}
		else
		{
			setMotorSpeed(leftarmMotor, 0);
			setMotorSpeed(rightarmMotor,0);
		}
//KouqiuMotor*****************************************************************


    resetMotorEncoder(leftkouqiuMotor);
		resetMotorEncoder(rightkouqiuMotor);

		if(getJoystickValue(BtnRUp) == 1)
		{
			setMotorTarget(leftkouqiuMotor,400, 100);
			setMotorTarget(rightkouqiuMotor, 400, 100);
			wait1Msec(1200);
			setMotorTarget(leftkouqiuMotor,0, 100);
			setMotorTarget(rightkouqiuMotor,0, 100);
			wait1Msec(900);

		}
	  else if(getJoystickValue(BtnRDown) == 1)
		{
     setMotorTarget(leftkouqiuMotor, 906, 100);
     setMotorTarget(rightkouqiuMotor, 906, 100);
     wait1Msec(2200);

		}

		else if(getJoystickValue(BtnLUp) == 1)
		{
     setMotorSpeed(leftkouqiuMotor, 100);
     setMotorSpeed(rightkouqiuMotor, 100);


		}

	  else if(getJoystickValue(BtnLDown) == 1)
		{
     setMotorSpeed(leftkouqiuMotor, -100);
     setMotorSpeed(rightkouqiuMotor, -100);
		}

		else
		{
			setMotorSpeed(leftkouqiuMotor, 0);
			setMotorSpeed(rightkouqiuMotor,0);
  	}





 //***************************************************************************
}
}
