#pragma config(Motor,  motor2,          robotCMotor,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int a = 0;
	bool EDownPress = true;
	while(true)
	{
		if (getJoystickValue(BtnEDown) == 1 && EDownPress == true)
		{
			a = a + 1;
			displayCenteredBigTextLine(3, "%d", a);
			resetMotorEncoder(robotCMotor);
			setMotorTarget(robotCMotor,360,100);


			EDownPress = false;
		}

		if (getJoystickValue(BtnEDown) == 0)
		{
			EDownPress = true;

		}
	}
}
